### ISSUE TITLE
Client crash on modded server, Forge 1.11.2...2315

### ISSUE THREAD

**Issue by Iiridayn** [legobmw99/Allomancy#18]
Assigned burn key to `\` (convenient on my keyboard) - works fine as misting, crashes client as mistborn.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  LoadingPlugin (Quark-r1.2-93.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 6/20/17 9:36 AM
Description: Ticking screen

java.lang.IndexOutOfBoundsException: 348
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.legobmw99.allomancy.gui.GUIMetalSelect.isKeyDown(GUIMetalSelect.java:234)
	at com.legobmw99.allomancy.gui.GUIMetalSelect.func_73876_c(GUIMetalSelect.java:203)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1715)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.legobmw99.allomancy.gui.GUIMetalSelect.isKeyDown(GUIMetalSelect.java:234)
	at com.legobmw99.allomancy.gui.GUIMetalSelect.func_73876_c(GUIMetalSelect.java:203)

-- Affected screen --
Details:
	Screen name: com.legobmw99.allomancy.gui.GUIMetalSelect

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Iiridayn'/3780, l='MpServer', x=100.50, y=66.00, z=256.50]]
	Chunk stats: MultiplayerChunkCache: 364, 364
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (96,64,256), Chunk: (at 0,4,0 in 6,16; contains blocks 96,0,256 to 111,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 15493 game time, 3721 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntitySkeleton['Skeleton'/3712, l='MpServer', x=109.50, y=33.00, z=256.50], EntitySkeleton['Skeleton'/3200, l='MpServer', x=117.73, y=37.00, z=250.50], EntitySkeleton['Skeleton'/3201, l='MpServer', x=128.50, y=33.00, z=248.50], EntityCreeper['Creeper'/3842, l='MpServer', x=32.50, y=19.00, z=255.50], EntityCreeper['Creeper'/3469, l='MpServer', x=50.41, y=18.00, z=310.30], EntityBat['Bat'/2829, l='MpServer', x=92.02, y=40.06, z=226.48], EntityBat['Bat'/3981, l='MpServer', x=53.46, y=14.67, z=312.40], EntityCreeper['Creeper'/3470, l='MpServer', x=48.50, y=18.00, z=310.50], EntityBat['Bat'/3982, l='MpServer', x=48.90, y=16.61, z=321.63], EntitySkeleton['Skeleton'/2959, l='MpServer', x=44.50, y=21.00, z=315.50], EntityCreeper['Creeper'/3471, l='MpServer', x=53.46, y=20.00, z=310.17], EntityFishCod['Cod'/3599, l='MpServer', x=116.50, y=59.00, z=332.50], EntityBat['Bat'/2832, l='MpServer', x=49.75, y=19.10, z=309.25], EntityBat['Bat'/3984, l='MpServer', x=48.51, y=17.00, z=319.32], EntitySkeleton['Skeleton'/3350, l='MpServer', x=30.50, y=28.00, z=312.50], EntitySkeleton['Skeleton'/3351, l='MpServer', x=32.50, y=28.00, z=310.50], EntitySpider['Spider'/3366, l='MpServer', x=41.50, y=16.00, z=214.50], EntityBat['Bat'/2600, l='MpServer', x=89.75, y=16.10, z=330.41], EntityFishCod['Cod'/3755, l='MpServer', x=33.50, y=62.00, z=241.50], EntityFishCod['Cod'/3756, l='MpServer', x=35.50, y=62.00, z=239.50], EntityFishCod['Cod'/3757, l='MpServer', x=37.50, y=62.00, z=237.50], EntityZombieVillager['Zombie Villager'/2989, l='MpServer', x=50.18, y=18.00, z=316.49], EntitySkeleton['Skeleton'/3501, l='MpServer', x=85.50, y=14.00, z=332.50], EntityFishCod['Cod'/3758, l='MpServer', x=38.50, y=62.00, z=235.50], EntityWitch['Witch'/3123, l='MpServer', x=108.50, y=34.00, z=254.50], EntityWolf['Wolf'/56, l='MpServer', x=40.50, y=63.00, z=296.50], EntityWolf['Wolf'/57, l='MpServer', x=43.33, y=63.00, z=296.64], EntityWolf['Wolf'/58, l='MpServer', x=40.50, y=63.00, z=298.50], EntitySkeleton['Skeleton'/3258, l='MpServer', x=38.50, y=20.00, z=291.50], EntityWolf['Wolf'/59, l='MpServer', x=41.37, y=63.00, z=296.34], EntityCow['Cow'/61, l='MpServer', x=54.50, y=63.00, z=333.50], EntityCow['Cow'/62, l='MpServer', x=52.21, y=63.00, z=332.25], EntityEnderman['Enderman'/3902, l='MpServer', x=153.57, y=41.00, z=319.52], EntityCow['Cow'/63, l='MpServer', x=48.23, y=64.00, z=332.22], EntityCow['Cow'/64, l='MpServer', x=56.15, y=63.00, z=336.30], EntityFishCod['Cod'/3651, l='MpServer', x=23.50, y=62.00, z=241.50], EntitySpider['Spider'/2627, l='MpServer', x=120.14, y=38.10, z=253.30], EntityPlayerSP['Iiridayn'/3780, l='MpServer', x=100.50, y=66.00, z=256.50], EntityFishCod['Cod'/3652, l='MpServer', x=26.50, y=62.00, z=244.50], EntitySkeleton['Skeleton'/2629, l='MpServer', x=125.48, y=33.00, z=249.60], EntityFishCod['Cod'/4037, l='MpServer', x=21.50, y=59.00, z=251.50], EntityAshen['Ashen'/3398, l='MpServer', x=33.50, y=16.00, z=213.50], EntityFishCod['Cod'/4038, l='MpServer', x=23.50, y=59.00, z=254.50], EntityEnderman['Enderman'/3399, l='MpServer', x=31.59, y=36.00, z=334.49], EntityCreeper['Creeper'/3400, l='MpServer', x=35.50, y=34.00, z=335.50], EntitySkeleton['Skeleton'/2765, l='MpServer', x=127.50, y=44.00, z=275.50], EntityBat['Bat'/3917, l='MpServer', x=122.48, y=26.05, z=263.76], EntityCreeper['Creeper'/3278, l='MpServer', x=52.16, y=55.00, z=224.50], EntitySkeleton['Skeleton'/3281, l='MpServer', x=47.50, y=54.00, z=220.50], EntityPig['Pig'/86, l='MpServer', x=120.50, y=80.00, z=215.50], EntityPig['Pig'/87, l='MpServer', x=121.50, y=80.00, z=215.50], EntityPig['Pig'/88, l='MpServer', x=121.50, y=80.00, z=215.50], EntityPig['Pig'/89, l='MpServer', x=126.30, y=84.00, z=209.62], EntityItem['item.tile.mushroom5'/90, l='MpServer', x=122.13, y=17.00, z=265.77], EntityBat['Bat'/2654, l='MpServer', x=46.64, y=18.73, z=306.25], EntityPig['Pig'/95, l='MpServer', x=157.60, y=68.00, z=243.59], EntityPig['Pig'/96, l='MpServer', x=163.33, y=71.00, z=239.49], EntityPig['Pig'/97, l='MpServer', x=156.50, y=67.00, z=247.50], EntityPig['Pig'/98, l='MpServer', x=158.50, y=68.00, z=245.50], EntityItem['item.tile.mushroom12'/3555, l='MpServer', x=127.88, y=11.00, z=251.37], EntityPig['Pig'/99, l='MpServer', x=170.38, y=72.00, z=277.74], EntityFishCod['Cod'/3684, l='MpServer', x=127.50, y=17.00, z=267.50], EntityPig['Pig'/100, l='MpServer', x=160.50, y=76.00, z=282.50], EntityBat['Bat'/2917, l='MpServer', x=27.27, y=38.02, z=216.26], EntityPig['Pig'/101, l='MpServer', x=159.50, y=75.00, z=280.50], EntityAshen['Ashen'/3046, l='MpServer', x=54.50, y=18.00, z=327.50], EntityPig['Pig'/102, l='MpServer', x=160.50, y=76.00, z=282.50], EntityZombieVillager['Zombie Villager'/3047, l='MpServer', x=53.50, y=18.00, z=327.50], EntityZombieVillager['Zombie Villager'/3048, l='MpServer', x=53.50, y=18.00, z=327.50], EntityFishCod['Cod'/3689, l='MpServer', x=22.50, y=62.00, z=267.50], EntityFishCod['Cod'/3690, l='MpServer', x=21.50, y=62.00, z=271.50], EntityFishCod['Cod'/3691, l='MpServer', x=28.50, y=62.00, z=268.50], EntityFishCod['Cod'/3692, l='MpServer', x=35.50, y=62.00, z=255.50], EntityFishCod['Cod'/3693, l='MpServer', x=34.50, y=62.00, z=258.50], EntityFishCod['Cod'/3694, l='MpServer', x=34.45, y=62.00, z=256.07], EntityFishCod['Cod'/3695, l='MpServer', x=38.50, y=62.00, z=263.50], EntityFishSalmon['Salmon'/3568, l='MpServer', x=118.74, y=59.35, z=333.16], EntityFishSalmon['Salmon'/3697, l='MpServer', x=129.50, y=59.00, z=333.50], EntityFishSalmon['Salmon'/3698, l='MpServer', x=126.50, y=59.00, z=334.50], EntityBat['Bat'/3954, l='MpServer', x=28.49, y=21.64, z=251.51], EntitySkeleton['Skeleton'/3059, l='MpServer', x=66.50, y=23.00, z=320.73], EntitySkeleton['Skeleton'/3060, l='MpServer', x=76.27, y=26.00, z=333.49], EntityCreeper['Creeper'/3062, l='MpServer', x=111.50, y=23.00, z=263.50], EntityCreeper['Creeper'/3319, l='MpServer', x=43.50, y=15.00, z=213.50], EntityCreeper['Creeper'/3321, l='MpServer', x=22.50, y=21.00, z=244.50], EntityZombie['Zombie'/3065, l='MpServer', x=157.50, y=72.00, z=288.50], EntityFishCod['Cod'/3709, l='MpServer', x=35.50, y=62.00, z=220.50], EntityFishCod['Cod'/3710, l='MpServer', x=33.50, y=62.00, z=221.50], EntityFishCod['Cod'/3711, l='MpServer', x=33.50, y=62.00, z=220.50], EntitySkeleton['Skeleton'/3071, l='MpServer', x=88.50, y=15.00, z=305.50], EntitySkeleton['Skeleton'/3199, l='MpServer', x=126.18, y=33.00, z=249.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.11.5-1-ARCH
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 100229944 bytes (95 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 68 mods loaded, 68 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315.jar) 
	UCHIJA	forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJA	uncraftingtable{1.7.2} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.2.jar) 
	UCHIJA	allomancy{2.7.0} [Allomancy] (allomancy-2.7.0b.jar) 
	UCHIJA	baubles{1.4.5} [Baubles] (Baubles-1.11-1.4.5.jar) 
	UCHIJA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.4.jar) 
	UCHIJA	flyringbaublemod{0.2.4_1.11.2-6570ea2} [AngelRing 2 Bauble] (angelRingToBauble-1.11.2-0.2.4.24+6570ea2.jar) 
	UCHIJA	jei{4.5.0.287} [Just Enough Items] (jei_1.11.2-4.5.0.287.jar) 
	UCHIJA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJA	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCHIJA	quark{r1.2-93} [Quark] (Quark-r1.2-93.jar) 
	UCHIJA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJA	base{2.0.0} [B.A.S.E] (base-1.11.2-2.0.0.jar) 
	UCHIJA	baubleshud{4.0.2} [Baubles-Hud] (BaublesHud-1.11.2-4.0.2.jar) 
	UCHIJA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
	UCHIJA	botania{r1.9-344} [Botania] (Botania r1.9-344.jar) 
	UCHIJA	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJA	charcoal_pit{1.3_11} [Charcoal Pit] (CharcoalPit-[1.11.2]-1.3_11.jar) 
	UCHIJA	chesttransporter{2.7.9} [Chest Transporter] (ChestTransporter-1.11.2-2.7.9.jar) 
	UCHIJA	clumps{2.0.0} [Clumps] (Clumps-2.0.0.jar) 
	UCHIJA	codechickenlib{2.7.0.268} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UCHIJA	craftingtweaks{7.1.9} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.9.jar) 
	UCHIJA	deathcounter{1.0.0} [DeathCounter] (DeathCounter-1.11-1.0.0.jar) 
	UCHIJA	deathquotes{1.2.0} [Death Quotes] (DeathQuotes-1.2.0-mc1.11.2-forge.jar) 
	UCHIJA	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.2-MC1.11.2.jar) 
	UCHIJA	fecm{1.0.0} [Elytra Crafting Recipe Mod] (Elytra Crafting Mod-1.0.0.jar) 
	UCHIJA	csb_ench_table{1.1} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.11-1.1.jar) 
	UCHIJA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.1.114-universal.jar) 
	UCHIJA	exu2cer{1.0} [ExU2 - CER] (exu2cer-1.11.2-1.0.jar) 
	UCHIJA	fasterladderclimbing{0.1-118} [Faster Ladder Climbing] (FasterLadderClimbing-1.11-0.1-118.jar) 
	UCHIJA	gobackpacks{1.1.1} [Good Old Backpacks] (GoodOldBackpacks-1.1.1.jar) 
	UCHIJA	helpfixer{1.4+17} [HelpFixer] (HelpFixer-1.11-1.4+17.jar) 
	UCHIJA	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.11.2.jar) 
	UCHIJA	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.11.2-0.11.0.jar) 
	UCHIJA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJA	jaff{1.6_for_1.11.2} [Just a Few Fish] (JustAFewFish-1.6_for_1.11.2.jar) 
	UCHIJA	justenoughbuttons{1.11.2-1.4.6} [Just Enough Buttons] (justenoughbuttons-1.11.2-1.4.6.jar) 
	UCHIJA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.0.4-1.11.2.jar) 
	UCHIJA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJA	modnametooltip{1.7.1} [Mod Name Tooltip] (modnametooltip_1.11-1.7.1.jar) 
	UCHIJA	moreplayermodels{1.11.0} [MorePlayerModels] (MorePlayerModels_1.11.2(26jan17).jar) 
	UCHIJA	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus-1.11.2-3.2.14.jar) 
	UCHIJA	natura{1.11.2-4.2.0.20} [Natura] (natura-1.11.2-4.2.0.20.jar) 
	UCHIJA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCHIJA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJA	scannable{1.4.0.23} [Scannable] (Scannable-MC1.11.2-1.4.0.23.jar) 
	UCHIJA	sophisticatedwolves{3.8.0} [Sophisticated Wolves] (SophisticatedWolves-1.11.2-3.8.0.jar) 
	UCHIJA	storagedrawers{1.11.2-4.2.9} [Storage Drawers] (StorageDrawers-1.11.2-4.2.9.jar) 
	UCHIJA	supercraftingframe{1.2.1.89} [Super Crafting Frame] (supercraftingframe-1.11-1.2.1.89.jar) 
	UCHIJA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	UCHIJA	supersoundmuffler{1.0.1.4} [Super Sound Muffler] (supersoundmuffler-1.11.2-1.0.1.4.jar) 
	UCHIJA	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCHIJA	tinkersaddons{1.0.5} [Tinkers' Addons] (Tinkers' Addons-1.11.x-1.0.5.jar) 
	UCHIJA	translocator{2.3.0.61} [Translocator] (Translocators-1.11.2-2.3.0.61-universal.jar) 
	UCHIJA	teleporter{1.6.2} [Vanilla-Inspired Teleporters] (VanillaTeleporter-1.11-1.6.2.jar) 
	UCHIJA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJA	villagenames{1.11.2-1.0} [Village Names] (VillageNames-1.11.2-1.0.jar) 
	UCHIJA	visiblearmorslots{3.1.1} [Visible Armor Slots] (VisibleArmorSlots[1.11.2]-3.1.1.jar) 
	UCHIJA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJA	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
LoadingPlugin (Quark-r1.2-93.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.22' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	translocator Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2315
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.22, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Phenom(tm) II X4 955 Processor
```

**Comment by legobmw99** [comment]
I can't recreate this in my test environment. Can you think of anything that might be affect this? You mentioned a nonstandard keyboard layout?

**Comment by Iiridayn** [comment]
I'm using an [Ergodox](https://www.ergodox.io/) with the original Ben Blazak style firmware - so the scan codes should be pretty normal regardless of physical key assigned. I'm running openjdk8 in Arch Linux, and have a moderately large quantity of other mods installed; might be interference from one of them. Any thoughts about potential culprits? I can try taking them out, but it'd be a slow binary search to try to nail it down that way. I could also try another key, something to the right perhaps, fewer conflicts that way, and see if an alphabet letter triggers it. What else do you think might cause it?

**Comment by legobmw99** [comment]
The cause of it is fairly obvious in the crash log, it just doesn't make any sense. Basically, the Keyboard functionality in the engine assigns each key a code, 0-255. 

For some reason, your `\` key is returning a code of **348**, which is too big and the game crashes.
Normally, `\` would be key 43

Now, this is interesting to me, because it appears the character you included in your original issue `\` is not the same character produced by my backslash button, `\`. This makes me suspect your keyboard's firmware is using the wrong character for that key, and the character it is using it not supported by the LWJGL Keyboard api

**Comment by legobmw99** [comment]
A bit more digging makes it seem like your character is U+FE68 'SMALL REVERSE SOLIDUS', rather than U+005C 'REVERSE SOLIDUS'

**Comment by Iiridayn** [comment]
Either way I'll test it - you have a link I can use or a simple app I can compile to test my Java scancodes? I have the same keyboard here in the office, though it's attached to a Windows OS.

However, if nothing else the code shouldn't crash from unexpected input :).

**Comment by legobmw99** [comment]
There isn't a utility that I can find, but the issue would be larger than just Java, so something like this [Javascript tester](http://keycode.info/) should work. The standard Javascript keycode for a backslash is 220, and if my theory is right you won't receive that as a response

**Comment by Iiridayn** [comment]
Got 220 - not surprising, since the keyboard works fine with everything else :).

**Comment by legobmw99** [comment]
Well, in that case, there is no conceivable reason the mod should be crashing. I would try the same thing when you get back to your other setup, but if it is all normal I don't know why you would have a crash while I wouldn't

**Comment by Iiridayn** [comment]
Might be the different Java/OS - unless you are also using openjdk8 on Arch Linux. Might also be some mod which grabs the keycode and modifies it when testing it, if treated as a reference (in which case you still shouldn't crash, but that mod would have much more to fix). I've shot myself in the foot enough times (once in particular springs to mind) modifying what I didn't realize was a reference :/.

**Comment by legobmw99** [comment]
The different java versions wouldn't make a difference, the crash is in LWJGL, which is tied to your minecraft installation and will always be the same version as my own. It's possible it's a negative interaction with another mod, but key codes are passed around as ints, so it likely is not a reference issue. 

I can't change the LWJGL methods, so the best I could do is error check the key codes to make sure they are less than 255, but the method in question _must return something_, so the best case solution on my end would result in the key not working **at all,** just quietly doing nothing instead of crashing (which I once again can't even replicate). That is certainly better, but won't allow you to use the key you want

**Comment by Iiridayn** [comment]
I agree - the documentation for that method does explicitly state that it returns an `Integer` - not a `byte` (whatever an 8 bit datatype is in Java) - so checking for an out of bound and ignoring if wrong is still needed. I'd hold off closing this until I can test some letter keys in minecraft and binary search the mods to track down the cause.

**Comment by Iiridayn** [comment]
Actually - for all I know your change could work. Mind slinging me a jar, or is it pretty simple to compile? I've had trouble getting iChun's mods compiling, so "once bitten", etc.

**Comment by legobmw99** [comment]
The only change made was switching to a method that already checked to see if the code was between 0 and 255, it will stop crashes but would not allow a key outside the normal range to actually _do_ anything.

Compiling is pretty easy, standard `gradle build` should do it, if you have a recent-enough JDK installed

**Comment by Iiridayn** [comment]
Can confirm that key works fine with Baubles and other mods, but other keys work fine with the allomancy mod... Sigh. Will try the build.

**Comment by Iiridayn** [comment]
Can confirm reproducible client side crash is gone with commit, though the menu sorta starts sliding out still. I suspect there are multiple keycodes generating somehow - but doesn't matter nearly as much as a crash, this is recoverable, user just picks another binding and doesn't file a report :). :+1:
