### ISSUE TITLE
Server Crash - Capability not attached

### ISSUE THREAD

**Issue by Rutes** [legobmw99/Allomancy#57]
This might be a mod cross-compatibility issue, but I figured I would post here in case there is some obvious fix on Allomancy's side.

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/9/21, 11:50 AM
Description: Exception in server tick loop

java.lang.RuntimeException: Capability not attached!
	at com.legobmw99.allomancy.modules.powers.util.AllomancyCapability.lambda$forPlayer$1(AllomancyCapability.java:108) ~[allomancy:4.2.1] {re:classloading,pl:capability_inject_definalize:A}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:296) ~[forge:?] {re:mixin,re:classloading}
	at com.legobmw99.allomancy.modules.powers.util.AllomancyCapability.forPlayer(AllomancyCapability.java:108) ~[allomancy:4.2.1] {re:classloading,pl:capability_inject_definalize:A}
	at com.legobmw99.allomancy.modules.powers.handlers.CommonEventHandler.onDamage(CommonEventHandler.java:175) ~[allomancy:4.2.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_790_CommonEventHandler_onDamage_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362) ~[forge:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70665_d(PlayerEntity.java:871) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.ma.entities.faction.EntitySpellbreaker.damageEntity(EntitySpellbreaker.java:203) ~[mana-and-artifice:1.3.0.2] {re:classloading}
	at com.ma.entities.faction.EntitySpellbreaker.handleDelayCallback(EntitySpellbreaker.java:257) ~[mana-and-artifice:1.3.0.2] {re:classloading}
	at com.ma.events.delayed.TimedDelayedEvent.tick(TimedDelayedEvent.java:23) ~[mana-and-artifice:1.3.0.2] {re:classloading}
	at com.ma.events.delayed.DelayedEventQueue.worldTick(DelayedEventQueue.java:30) ~[mana-and-artifice:1.3.0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_443_DelayedEventQueue_worldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:95) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}
```

**Comment by legobmw99** [comment]
Could I get a complete list of mods and versions? 

What was occurring when the crash was triggered?
