### ISSUE TITLE
Crash while playing on server

### ISSUE THREAD

**Issue by jamesipod** [legobmw99/Allomancy#93]
I think I had tin on, went to a village and got this error: 

`---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-12-04 17:20:17
Description: Unexpected error

java.lang.NullPointerException: Registry Object not present: allomancy:sound_particle
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.20.1-47.2.16-universal.jar%23381!/:?] {re:mixin,re:classloading}
	at com.legobmw99.allomancy.modules.powers.client.particle.SoundParticleData.m_6012_(SoundParticleData.java:38) ~[allomancy-4.6.6.jar%23268!/:4.6.6] {re:classloading}
	at net.minecraft.client.particle.ParticleEngine.m_107395_(ParticleEngine.java:322) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleEngine.m_107370_(ParticleEngine.java:311) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.legobmw99.allomancy.modules.powers.client.ClientEventHandler.lambda$onSound$7(ClientEventHandler.java:407) ~[allomancy-4.6.6.jar%23268!/:4.6.6] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.2.16-universal.jar%23381!/:?] {re:mixin,re:classloading}
	at com.legobmw99.allomancy.modules.powers.client.ClientEventHandler.onSound(ClientEventHandler.java:389) ~[allomancy-4.6.6.jar%23268!/:4.6.6] {re:classloading}
	at com.legobmw99.allomancy.modules.powers.client.__ClientEventHandler_onSound_PlaySoundEvent.invoke(.dynamic) ~[allomancy-4.6.6.jar%23268!/:4.6.6] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.playSound(ForgeHooksClient.java:408) ~[forge-1.20.1-47.2.16-universal.jar%23381!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.sounds.SoundEngine.m_120312_(SoundEngine.java:329) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundEngine.m_120326_(SoundEngine.java:300) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundEngine.m_120302_(SoundEngine.java:223) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundManager.m_120389_(SoundManager.java:272) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1824) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:immersive_armors.mixins.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:immersive_armors.mixins.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:immersive_armors.mixins.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[client-1.20.1-20230612.114412-srg.jar%23376!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.16.jar%23104!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.16.jar%23104!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.16.jar%23104!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-`

**Comment by legobmw99** [comment]
I believe this is resolved in the latest version
